// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xblzylvmqorwmxcphsan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibHp5bHZtcW9yd214Y3Boc2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTYzNDUsImV4cCI6MjA2OTM3MjM0NX0.X6QtzU_OeJWylhIpnb2FoCxxI4sEYiZCysuUv8WcHUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});